In [1]:
import numpy as np
import pandas as pd


In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


In [3]:
# 샘플 데이터 생성
data = {
    'X': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'y': [3, 4, 2, 5, 6, 7, 8, 9, 10, 12]
}

df = pd.DataFrame(data)


In [4]:
df

X   y
0   1   3
1   2   4
2   3   2
3   4   5
4   5   6
5   6   7
6   7   8
7   8   9
8   9  10
9  10  12

In [8]:
x = df[['X']] ## X는 여러개일 수 있으므로 벡터로 
y = df['y'] ## y 는 1개씩이므로 스칼라로

In [9]:
X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=0.2)

In [10]:
model = LinearRegression()

In [11]:
model.fit(X_train, y_train)

LinearRegression()

In [12]:
y_pred = model.predict(X_test)

In [13]:
y_pred

array([5.92647059, 2.70588235])

In [14]:
y_test

4    6
1    4
Name: y, dtype: int64

In [16]:
model.coef_
model.intercept_

0.5588235294117636

In [17]:
import statsmodels.api as sm

In [18]:
model = sm.OLS(y_train, X_train)

In [20]:
result = model.fit()

In [21]:
result.summary()

c:\Users\msong\anaconda3\envs\py3_11_8\Lib\site-packages\scipy\stats\_axis_nan_policy.py:531: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  res = hypotest_fun_out(*samples, **kwds)


<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.987
Model:                            OLS   Adj. R-squared (uncentered):              0.985
Method:                 Least Squares   F-statistic:                              538.4
Date:                Wed, 25 Sep 2024   Prob (F-statistic):                    7.01e-08
Time:                        09:01:21   Log-Likelihood:                         -10.273
No. Observations:                   8   AIC:                                      22.55
Df Residuals:                       7   BIC:                                      22.63
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
X              1.1489      0.050     23.203      0.000       1.032       1.266
==============================================================================
Omnibus:                        2.150   Durbin-Watson:                   2.830
Prob(Omnibus):                  0.341   Jarque-Bera (JB):                0.156
Skew:                           0.294   Prob(JB):                        0.925
Kurtosis:                       3.349   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [22]:
!pip install mlxtend

   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
    --------------------------------------- 0.0/1.4 MB 217.9 kB/s eta 0:00:07
    --------------------------------------- 0.0/1.4 MB 217.9 kB/s eta 0:00:07
    --------------------------------------- 0.0/1.4 MB 131.3 kB/s eta 0:00:11
    --------------------------------------- 0.0/1.4 MB 131.3 kB/s eta 0:00:11
    --------------------------------------- 0.0/1.4 MB 131.3 kB/s eta 0:00:11
   - -------------------------------------- 0.0/1.4 MB 109.3 kB/s eta 0:00:13
   - -------------------------------------- 0.1/1.4 MB 149.3 kB/s eta 0:00:10
   - -------------------------------------- 0.1/1.4 MB 149.3 kB/s eta 0:00:10
   -- ------------------------------------- 0.1/1.4 MB 187.5 kB/s eta 0:00:08
   --- ------------------------------------ 0.1/1.4 MB 211.6 kB/s eta 0:00:07
   --- ------

In [29]:
from mlxtend.feature_selection import SequentialFeatureSelector as SFS

In [24]:
# 샘플 데이터 생성
data = {
    'X1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'X2': [5, 3, 6, 8, 12, 9, 7, 11, 15, 16],
    'X3': [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
    'y': [3, 4, 2, 5, 6, 7, 8, 9, 10, 12]
}

df = pd.DataFrame(data)


In [25]:
df

X1  X2  X3   y
0   1   5  10   3
1   2   3  11   4
2   3   6  12   2
3   4   8  13   5
4   5  12  14   6
5   6   9  15   7
6   7   7  16   8
7   8  11  17   9
8   9  15  18  10
9  10  16  19  12

In [26]:
# 독립 변수와 종속 변수 나누기
X = df[['X1', 'X2', 'X3']]
y = df['y']

In [27]:
lr = LinearRegression()

In [37]:
sfs = SFS(lr, k_features='best', forward=True, floating=False, scoring='r2', cv=5) ## 전진선택
sfs = SFS(lr, k_features='best', forward=False, floating=False, scoring='r2', cv=5) ## 후진 제거
sfs = SFS(lr, k_features='best', forward=True, floating=True, scoring='r2', cv=5) ## stepwise


In [39]:
sfs = sfs.fit(X, y)

c:\Users\msong\anaconda3\envs\py3_11_8\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
c:\Users\msong\anaconda3\envs\py3_11_8\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
c:\Users\msong\anaconda3\envs\py3_11_8\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
c:\Users\msong\anaconda3\envs\py3_11_8\Lib\site-packages\sklearn\model_selection\_validation.py:73: FutureWarning: `fit_params` is deprecated and will be removed in version 1.6. Pass parameters via `params` instead.
  warnings.warn(
c:\Users\msong\anaconda3\envs\py3_11_8\Lib\site-packages\sklearn\mod

In [40]:
selected = sfs.k_feature_names_

In [34]:
selected

('X1', 'X3')

In [4]:
import pandas as pd

In [5]:
## Logistic regression
data = {
    'X1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'X2': [5, 3, 6, 8, 12, 9, 7, 11, 15, 16],
    'y': [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
}

df = pd.DataFrame(data)


In [6]:
# 독립 변수와 종속 변수 나누기
X = df[['X1', 'X2']]
y = df['y']


In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
logistic_model = LogisticRegression()
logistic_model.fit(X, y)

LogisticRegression()

In [9]:
y_pred_logistic = logistic_model.predict(X)

In [10]:
y_pred_logistic

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int64)

In [12]:
y

0    0
1    0
2    0
3    0
4    0
5    1
6    1
7    1
8    1
9    1
Name: y, dtype: int64

In [13]:
logistic_model.predict_proba(X)

array([[0.99348374, 0.00651626],
       [0.97086723, 0.02913277],
       [0.93504105, 0.06495895],
       [0.84437186, 0.15562814],
       [0.72866349, 0.27133651],
       [0.33872992, 0.66127008],
       [0.10069277, 0.89930723],
       [0.05250954, 0.94749046],
       [0.02669832, 0.97330168],
       [0.0089419 , 0.9910581 ]])